basePath: /
host: localhost:8000
info:
  contact:
    email: ivandersalvadorruiz@gmail.com
    name: Ivander
    url: https://linkedin.com/in/ivandersr
  description: Products API with Authentication
  license:
    name: MIT
    url: https://opensource.org/license/mit
  termsOfService: http://swagger.io/terms
  title: Products API Go
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
